services:
  postgres:
    image: postgres:17
    container_name: neuroquest-postgres

    environment:
      POSTGRES_DB: neuroquest
      POSTGRES_USER: neuroquest
      POSTGRES_PASSWORD: neuroquest

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: