"""add envelope mission models

Revision ID: 1bf8f2225324
Revises: b8287d194388
Create Date: 2026-09-24 08:49:57.504542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bf8f2225324'
down_revision: Union[str, Sequence[str], None] = 'b8287d194388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envelope_missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sector_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('unlock_condition', sa.Text(), nullable=True),
    sa.Column('validation_type', sa.Enum('PHOTO', 'TEXT', name='mission_validation_type'), nullable=False),
    sa.Column('validation_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'APPROVED', 'REJECTED', name='mission_attempt_status'), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('text_answer', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mission_id'], ['envelope_missions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mission_attempts')
    op.drop_table('envelope_missions')
    # ### end Alembic commands ###
