"""add parent accounts and link players to a parent

Revision ID: 6ef8f8a48085
Revises: c75f776164a3
Create Date: 2026-09-27 07:52:58.925227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef8f8a48085'
down_revision: Union[str, Sequence[str], None] = 'c75f776164a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('players', sa.Column('parent_id', sa.UUID(), nullable=False))
    op.create_foreign_key(
        'fk_players_parent_id_parent_accounts',
        'players', 'parent_accounts', ['parent_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        'fk_players_parent_id_parent_accounts', 'players', type_='foreignkey'
    )
    op.drop_column('players', 'parent_id')
    op.drop_table('parent_accounts')
    # ### end Alembic commands ###
