"""add current_step to mission attempts

Revision ID: 93b3d9bad6df
Revises: 1bf8f2225324
Create Date: 2026-09-26 00:43:03.382637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b3d9bad6df'
down_revision: Union[str, Sequence[str], None] = '1bf8f2225324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mission_attempts",
        sa.Column("current_step", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column("mission_attempts", "current_step", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mission_attempts', 'current_step')
    # ### end Alembic commands ###
