"""add quest graph models

Revision ID: ab0c936f17c9
Revises: e1ace623db47
Create Date: 2026-09-23 16:21:26.881701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab0c936f17c9'
down_revision: Union[str, Sequence[str], None] = 'e1ace623db47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_badge', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector_id', sa.UUID(), nullable=False),
    sa.Column('start_node_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quest_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CHOICE', 'COMPLETION', name='quest_node_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('choices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=5), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('consequence_text', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='choice_outcome'), nullable=False),
    sa.Column('status_label', sa.String(length=150), nullable=True),
    sa.Column('lesson_text', sa.Text(), nullable=True),
    sa.Column('achievement_id', sa.UUID(), nullable=True),
    sa.Column('unlock_title', sa.String(length=200), nullable=True),
    sa.Column('unlock_description', sa.Text(), nullable=True),
    sa.Column('next_node_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['next_node_id'], ['quest_nodes.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['quest_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choices')
    op.drop_table('quest_nodes')
    op.drop_table('quests')
    op.drop_table('achievements')
    # ### end Alembic commands ###
