"""add completion reward fields to quest node

Revision ID: b8287d194388
Revises: 258966fb743f
Create Date: 2026-09-23 21:16:54.996199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8287d194388'
down_revision: Union[str, Sequence[str], None] = '258966fb743f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_nodes', sa.Column('achievement_id', sa.UUID(), nullable=True))
    op.add_column('quest_nodes', sa.Column('unlock_title', sa.String(length=200), nullable=True))
    op.add_column('quest_nodes', sa.Column('unlock_description', sa.Text(), nullable=True))
    op.create_foreign_key(
        "fk_quest_nodes_achievement_id_achievements",
        "quest_nodes",
        "achievements",
        ["achievement_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "fk_quest_nodes_achievement_id_achievements", "quest_nodes", type_="foreignkey"
    )
    op.drop_column('quest_nodes', 'unlock_description')
    op.drop_column('quest_nodes', 'unlock_title')
    op.drop_column('quest_nodes', 'achievement_id')
    # ### end Alembic commands ###
