"""add quest card and master code letter models

Revision ID: b8602f56a31d
Revises: 3e1919a18504
Create Date: 2026-09-23 16:22:14.240466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8602f56a31d'
down_revision: Union[str, Sequence[str], None] = '3e1919a18504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sector_id', sa.UUID(), nullable=False),
    sa.Column('quest_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('intro_text', sa.Text(), nullable=False),
    sa.Column('qr_token', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_token'),
    sa.UniqueConstraint('quest_id')
    )
    op.create_table('master_code_letters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quest_card_id', sa.UUID(), nullable=False),
    sa.Column('letter', sa.String(length=2), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quest_card_id'], ['quest_cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position'),
    sa.UniqueConstraint('quest_card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_code_letters')
    op.drop_table('quest_cards')
    # ### end Alembic commands ###
