"""add terms consent fields to parent account

Revision ID: d0e5b2b1ddd4
Revises: 6ef8f8a48085
Create Date: 2026-10-05 05:45:00.635062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e5b2b1ddd4'
down_revision: Union[str, Sequence[str], None] = '6ef8f8a48085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_accounts', sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('parent_accounts', sa.Column('terms_version', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent_accounts', 'terms_version')
    op.drop_column('parent_accounts', 'terms_accepted_at')
    # ### end Alembic commands ###
